import { Metadata } from "next";
import "../styles/main.css";
import { Inter } from "next/font/google";
import Providers from "@/context/Providers";

const inter = Inter({subsets:["latin"]});

export const metadata: Metadata = {
  title: "Ecommerce Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={inter.className}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
